function [ brodmannlabels, brodmannlobes ] = BrodmannLabels( )
% gives the brodmann labels indexed by position in cell  
% grabbed labels and corresponding numbers from wikipedia, but they seem to
% match up with the ROI names in our list 
brodmannlabels = {'Primary Somatosensory Cortex (B1)',...
    'Primary Somatosensory Cortex (B2)',...
    'Primary Somatosensory Cortex (B2)',...
    'Primary Motor Cortex (B4)',...
    'Somatosensory Association Cortex (B5)', ...
    'Premotor Cortex (B6)', ...
    'Somatosensory Association Cortex (B7)', ...
    'Frontal Eye Fields (B8)', ...
    'Dorsolateral Prefrontal Cortex (B9)', ...
    'Anterior Prefrontal Cortex (B10)', ...
    'Orbitofrontal Area (B11)', ...
    'Orbitofrontal Area (B12)', ...
    'Insular Cortex (B13)', ...
    'Insular Cortex (B14)', ...
    'Anterior Temporal Lobe (B15)', ...
    'Insular Cortex (B16)', ...
    'Primary Visual Cortex (B17)', ...
    'Secondary Visual Cortex (B18)', ...
    'Associative Visual Cortex (B19)', ...
    'Inferior Temproal Gyrus (B20)', ...
    'Middle Temporal Gyrus (B21)', ...
    'Superior Temporal Gyrus (B22)', ...
    'Ventral Posterior Limbic Cortex (B23)', ...
    'Ventral Anterior Limbic Cortex (B24)', ...
    'Subgenual Area (B25)', ...
    'Ectosplenial Retrosplenial Region (B26)', ...
    'Piriform Cortex (B27)',...
    'Ventral Entorhinal Cortex (B28)', ...
    'Retrosplenial Limbic Cortex (B29)', ...
    'Limbic Cortex (B30)', ...
    'Dorsal Posterior Limbic Cortex (B31)', ...
    'Dorsal Anterior Limbic Cortex (B32)', ...
    'Anterior Limbic Cortex (B33)', ...
    'Dorsal Entorhinal Cortex (B34)', ...
    'Perirhinal Cotex (B35)', ...
    'Ectorhinal Area (B36)', ...
    'Fusiform Gyrus (B37)', ...
    'Temporopolar area (B38)', ...
    'Angular Gyrus (B39)', ...
    'Supramarginal Gyrus (B40)', ...
    'Auditory Cortex (B41)', ...
    'Auditory Cortex (B42)', ...
    'Primary Gustatory Cortex (B43)', ...
    'Pars Opercularis (B44)', ...
    'Pars Triangularis(B45)', ...
    'Dorsolateral Prefrontal Cortex (B46)', ...
    'Pars Orbitalis (B47)', ...
    'Retrosubicular Area (B48)', ...
    'Parasubicular Area (B49)', ...
    '', ...
    '', ...
    'Parainsular Area (B52)'
    };



brodmannlobes = {'Parietal',...
    'Parietal',...
    'Parietal',...
    'Frontal', ...
    'Parietal',...
    'Frontal', ...
    'Parietal',...
    'Frontal', ...
    'Frontal', ...
    'Frontal', ...
    'Frontal', ...
    'Frontal', ...
    'Insular', ...
    'Insular', ...
    'Temporal', ...
    'Insular', ...
    'Occipital',...
    'Occipital',...
    'Occipital',...
    'Temporal', ...
    'Temporal', ...
    'Temporal', ...
    'Limbic',...
    'Limbic',...
    'Frontal',...
    'Limbic',...
    'Limbic',...
    'Temporal',...
    'Limbic',...
    'Limbic',...
    'Limbic',...
    'Limbic',...
    'Limbic',...
    'Limbic',...
    'Temporal',...
    'Temporal',...
    'Temporal', ...
    'Temporal',...
    'Parietal',...
    'Parietal',...
    'Temporal',...
    'Temporal',...
    'Frontal',...
    'Frontal', ...
    'Frontal', ...
    'Frontal',...
    'Frontal',...
    'Temporal',...
    'Limbic',...
    '',...
    '',...
    'Temporal',...
    };
    
    

end

